apiVersion: v1
kind: ConfigMap
metadata:
  name: my1health-api-config
  namespace: my1health-api
data:
  APP_NAME: "My 1Health"
  APP_ENV: "production"
  APP_DEBUG: "true"
  APP_URL: "https://api.my1health.com"
  LOG_CHANNEL: "stdout"
  LOG_DEPRECATIONS_CHANNEL: null
  LOG_LEVEL: "debug"

  DB_CONNECTION: "mysql"
  DB_PORT: "3306"

  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "file"
  FILESYSTEM_DISK: "local"
  QUEUE_CONNECTION: "sync"
  SESSION_DRIVER: "file"
  SESSION_LIFETIME: "120"

  MEMCACHED_HOST: "127.0.0.1"

  REDIS_HOST: "127.0.0.1"
  REDIS_PASSWORD: null
  REDIS_PORT: "6379"

  MAIL_MAILER: smtp
  MAIL_HOST: mailpit
  MAIL_PORT: '1025'
  MAIL_USERNAME: null
  MAIL_PASSWORD: null
  MAIL_ENCRYPTION: null
  MAIL_FROM_ADDRESS: "hello@example.com"
  MAIL_FROM_NAME: "${APP_NAME}"

#   SERVER_PORT:
#   MY_1HEALTH_SITE_ROOT:
#
#   MY_1HEALTH_NOTIFICATIONS_URL:

  SCOUT_QUEUE: "true"

  PAYSTACK_VERIFICATION_ENDPOINT: https://api.paystack.co/transaction/verify
