apiVersion: apps/v1
kind: Deployment
metadata:
  name: my1health-api-deployment
  namespace: my1health-api
  labels:
    app: my1health-api
spec:
  selector:
    matchLabels:
      app: my1health-api
  template:
    metadata:
      namespace: my1health-api
      labels:
        app: my1health-api
    spec:
      containers:
        - name: my1health-api
          image: paulmuri/my1health-api:v1.0.0
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: my1health-api-config
#             - secretRef:
#                 name: my1health-api-secrets
#           resources:
#             requests:
#               memory: "64Mi"
#               cpu: "250m"
#             limits:
#               memory: "128Mi"
#               cpu: "500m"
#          readinessProbe:
#            httpGet:
#              path: /
#              port: 9000
#            initialDelaySeconds: 10
#            periodSeconds: 5
#          livenessProbe:
#            httpGet:
#              path: /
#              port: 9000
#            initialDelaySeconds: 30
#            periodSeconds: 15
