apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my1health-api-hpa
  namespace: my1health-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my1health-api-deployment
  minReplicas: 2  # Minimum number of replicas
  maxReplicas: 10  # Maximum number of replicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60  # Target average CPU utilization percentage
